name: common
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #logic
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.5.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  permission_handler: 11.3.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  #  flutter_image_compress: 2.3.0


  # di
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  get_it: ^8.0.2

  #network
  dio: ^5.7.0

  #localization
  easy_localization: ^3.0.7

  #UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  text_scroll: ^0.2.0
  reactive_forms: ^17.0.1
  fluttertoast: ^8.2.8
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  flutter_animate: ^4.5.1
  fluid_dialog: ^2.0.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  flutter_osm_plugin: ^1.3.6
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0
  catcher:
    git:
      url: https://github.com/AHMADMalbetar/catcher.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
